---
- name: Disable SELinux
  selinux:
    state: disabled
- name: Disable Swap Memory
  shell: swapoff -a
- name: Disable Firewalld
  service:
    name: firewalld
    state: stopped
  ignore_errors: true
- name: Install required packages
  include_tasks: packages.yml
  run_once: 'yes'
- name: Start service kubelet, if not started
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: 'yes'
