---
- name: Add Kubernetes yum repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: 'yes'
    gpgcheck: 'yes'
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
- name: Install kubeadm
  yum:
    name:
      - kubeadm
      - iproute-tc
      - bind-utils
    state: present
    update_cache: 'yes'
